### ISSUE TITLE
recursive option in pyproject is ignored

### ISSUE THREAD

**Issue by ceberam** [PyCQA/autoflake#160]
I have the autoflake option `recursive` in `pyproject.toml`:

```toml
[tool.autoflake]
in-place = true
remove-all-unused-imports = true
remove-unused-variables = true
expand-star-imports = true
recursive = true
```

and I was able to run autoflake recursively in my project directory (with `poetry`):

```
$ poetry run autoflake my_project_directory
```

This worked fine in version `1.6.1` and `1.7.0` but with version `1.7.1` I get the following error:

```
[Errno 21] Is a directory: 'my_project_directory'
```

It seems like autoflake does not pick up the option from `pyproject.toml` anymore.
