### ISSUE TITLE
Have pre-commit hook read config from `setup.cfg`

### ISSUE THREAD

**Issue by dstansby** [PyCQA/autoflake#191]
I'm currently using `autoflake` as a pre-commit hook, and would like it to read my `autoflake` configuration from `setup.cfg`. It seems like this isn't possible, and the `pre-commit` hook just has a default set of arguments instead.

It would be great if it was possible for the pre-commit hook to automatically read config from `setup.cfg` or `pyproject.toml` instead.

**Comment by fsouza** [comment]
@dstansby at this point I think it's unlikely that we'll change the default arguments, but you can override them in your pre-commit config and that should honor your setup.cfg/pyproject.toml. Something like:


```yaml
-   repo: https://github.com/PyCQA/autoflake
    rev: v2.0.0
    hooks:
    -   id: autoflake
        args: ["--in-place"]
```

(or `args: []` if you don't want pre-commit modifying your files)
