### ISSUE TITLE
(🎁) specify files in config file

### ISSUE THREAD

**Issue by KotlinIsland** [PyCQA/autoflake#239]
I want to specify the "files" option in my config file, so that I can invoke like: `👉 autoflake`.

```toml
[tool.autoflake]
files = ["scripts", "src"]
```
